Meteor.startup(function () {

  	if (Meteor.users.find({}).count() == 0) {
	    Accounts.createUser({username: 'ninakix', password: 'jello'})
    }
    
    if (Quotes.find().count() === 0) {
    	var currentQuote = Quotes.insert({"text": "In 2008, Duncan Watts published a paper that proved that it wasn’t actually a small, powerful group of influencers in that encouraged massive change. The masses basically adopted something when they collectively wanted it. While this is unfortunate for Gladwell, it leads us to this reminder that networks themselves have a preference, and they collectively filter and promote. In the infancy of the net, it was predicted that one day we would have a great collective discourse that would drive change. Sadly, this never happened, the networks propensity to act as a hive mind leaves us more polarized than curious. So given the limits of our own networks it becomes important to work across many desperate networks. When we think about how networks filter for content, we’ll do better spending time where there’s a large amount of anonymity and the community acts as a meritocracy.", "sourceURL": "http://colinraney.com/2013/02/luck-the-network/", "sourceTitle": "Luck & the Network", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Scott McCloud, in Understanding Comics: the Invisible Art, defines comics as “juxtaposed pictorial and other images in deliberate sequence, intended to convey information and/or to produce an aesthetic response in the viewer” (McCloud 9). Likewise, Eisner designates comics as a “sequential art,” referring mainly to the artist’s task of arranging “the sequence of events (or pictures) so as to bridge the gaps in action” (Eisner, 1985 38). The story of a graphic novel is told through a progression of frames, technically referred to as ‘panels.’ Panels “secure control of the reader’s attention and dictate the sequence in which the reader will follow the narrative” (Eisner, 1985 40).", "sourceURL": "http://lucian.uchicago.edu/blogs/mediatheory/keywords/graphic-novel/", "sourceTitle": "graphic novel | The Chicago School of Media Theory", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Social media, especially highly structured sites like Facebook, are partly akin to the amusement park in providing a controlled way to take risks with identity and behave in risky ways (stalking, sharing “too much,” etc.) and partly akin to old vicarious entertainments, only the risk-taking heroes are peers, not fictional characters or celebrities. They are instead the microfamous; they are ourselves. The commercial fantasies are about ourselves. Like the action at plush casinos where you get to play at high-rollerdom, this social media action is “at once vicarious and real.” The different social media sites offer different ways to calibrate this balance, but it is easy to get wrong and they encourage that we lose sight of the more far-reaching consequences of impulsive behavior. The vicarious thrill of being able to broadcast, to seize a moment of self-definition (which must be risky — shameful, if you buy into Eve Kosofsky Sedgwick’s gloss on Silvan Tomkins’s affect theory — to feel rich and true) is social media’s product for users.", "sourceURL": "http://thenewinquiry.com/blogs/marginal-utility/serious-action/", "sourceTitle": "Serious action – The New Inquiry", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "“Being careless is a choice, it’s choosing not to care.” Change means “being willing to peel back the veneer of my excuses.”", "sourceURL": "http://www.poynter.org/latest-news/mediawire/204005/jonah-lehrer-talks-about-plagiarism-at-knight-lunch/", "sourceTitle": "Jonah Lehrer earns $20,000 honorarium for talking about plagiarism at Knight lunch | Poynter.", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Slater seems impressed by this pitch, declaring that “the measure of power that [online connecting] abdicates to the user is unprecedented” and trumpeting the “choice and control provided by these revolutionary means.” But the only way to become empowered by this form of control is to accede to being controlled on a higher level. To capitalize on convenience and autonomy in a consumer marketplace, we must first allow our desires to be commodified and suppress the desires that don’t lend themselves to commodification.", "sourceURL": "http://thenewinquiry.com/essays/single-servings/", "sourceTitle": "Single Servings – The New Inquiry", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "To facilitate the shift in emphasis to data collection — and obfuscate the poorly aligned incentives between dating sites and their users — online dating, Slater reports, is rebranding itself as “social discovery.” Dating is just a specialized subset of the potential market for facilitating introductions. Social discovery denotes a kind of commodified serendipity that emphasizes the joy of users’ perpetually meeting people on the basis of a wide variety of ever-shifting interests — that is, opportunistically consuming them for their novelty.", "sourceURL": "http://thenewinquiry.com/essays/single-servings/", "sourceTitle": "Single Servings – The New Inquiry", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "“His was a chariot of pure intent in a city out of control,” Hockenberry remembers. “Design blew it all away for a moment.” And this matters, he adds, because “an object imbued with intent has power. It’s treasure; we’re drawn to it. An object devoid of intent is random, imitative, it repels us. It is junkmail to be thrown away. This is what we must demand of our lives, of our objects, of our things, our circumstances: living with intent.” - John Hockenberry's TED talk", "sourceURL": "http://scriptogr.am/ninakix/post/design-with-intent", "sourceTitle": "ninakix | Design with Intent", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Stacking a list of things by reverse-chronology is easy for computers, but my squishy human brain misses having more discrete units of time. Printed publications can be categorized by how they bracket time — dailys, weeklies, monthlies, quarterlies, annuals — and are as much tied to their pace of production as to their worldview of what is the most interesting span of time?", "sourceURL": "http://the-pastry-box-project.net/allen-tan/2013-january-23/", "sourceTitle": "The Pastry Box Project | 23 January 2013, baked by Allen Tan", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "A new study, titled “Major Memory for Microblogs” and published in this month’s edition of Memory & Cognition, reports on the results of experiments that show that the “trivial ephemera” that people share through Twitter and Facebook are actually much more memorable than, say, “sentences from books.” We have a “remarkable memory for microblogs,” the research indicates, because brief “status updates” are closer to “the largely spontaneous and natural emanations of the human mind” than are the more complex and carefully composed sentences found in literature. Because they resemble snippets of conversation, tweets and such-like seem to be “mind-ready formats.”", "sourceURL": "http://www.roughtype.com/?p=2513", "sourceTitle": "Me tweet pretty one day", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "But the fact that some gender differences can be manipulated, if not eliminated, by controlling for cultural norms suggests that the explanatory power of evolution can’t sustain itself when applied to mating behavior. This wouldn’t be the first time we’ve pushed these theories too far. How many stereotypical racial and ethnic differences, once declared evolutionarily determined under the banner of science, have been revealed instead as vestiges of power dynamics from earlier societies?", "sourceURL": "http://www.nytimes.com/2013/01/13/opinion/sunday/darwin-was-wrong-about-dating.html?partner=rssnyt&emc=rss&_r=3&pagewanted=all&", "sourceTitle": "Darwin Was Wrong About Dating", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "It's a departure from appreciating a singular moment. What that means is . . . the reason why we can appreciate art is because most art has a single resting point: canvas. It's painted. It's dried. It aspires to be perfect. The medium of the computer is continually shifting. It can shift at will, in a microsecond. Or an hour. There's no limit on how it can be taught to change.", "sourceURL": "http://www.nytimes.com/1999/07/27/science/a-conversation-with-john-maeda-when-mit-artist-shouts-his-painting-listens.html?pagewanted=all&src=pm", "sourceTitle": "A CONVERSATION WITH: JOHN MAEDA; When M.I.T. Artist Shouts, His 'Painting' Listens - New York Times", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Q. But lots of nonartists use computers for creating images . . . A. They are using it as a tool, but not as a material. And to use it as a tool, you need to understand the medium, which means understanding the technology. Young people are changing this, because they have grown up with computers.", "sourceURL": "http://www.nytimes.com/1999/07/27/science/a-conversation-with-john-maeda-when-mit-artist-shouts-his-painting-listens.html?pagewanted=all&src=pm", "sourceTitle": "A CONVERSATION WITH: JOHN MAEDA; When M.I.T. Artist Shouts, His 'Painting' Listens - New York Times", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "A. The problem is that most people can't just ''finish'' things with it. They have to use it to start them, also. For much of recent history, people have created with brush, ink, paper -- the materials of art. Now that they have begun creating with software and computers, the styles that emerge are homogeneous because the software is universal. Without being able to know how to program, you can't break out of the technology -- just like if you don't know how to use brush and ink, you're limited.", "sourceURL": "http://www.nytimes.com/1999/07/27/science/a-conversation-with-john-maeda-when-mit-artist-shouts-his-painting-listens.html?pagewanted=all&src=pm", "sourceTitle": "A CONVERSATION WITH: JOHN MAEDA; When M.I.T. Artist Shouts, His 'Painting' Listens - New York Times", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "I am unsure of what this intimacy with the improbable does to us. What happens if we spend all day exposed to the extremes of life, to a steady stream of the most improbable events, and try to run ordinary lives in a background hum of superlatives? What happens when the extraordinary becomes ordinary?", "sourceURL": "http://www.kk.org/thetechnium/archives/2013/01/the_improbable.php", "sourceTitle": "The Technium: The Improbable is the New Normal", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "We are not simply hedonic machines who thrive if supplied with things that tick certain boxes for sensory pleasure, aesthetic merit, and so on. We are knowing as well as sensing creatures, and knowing where things come from, and how their makers are treated, does and should affect how we feel about them. Chocolate made from cocoa beans grown by people in near slave conditions should taste more bitter than a fairly traded bar, even if it does not in a blind tasting. Blindness, far from making tests fair, actually robs us of knowledge of what is most important, while perpetuating the illusion that all that really matters is how it feels or seems at the moment of consumption.", "sourceURL": "http://www.aeonmagazine.com/being-human/julian-baggini-coffee-artisans/", "sourceTitle": "Julian Baggini – The art of coffee", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "what Nespresso had really done was to look at the coffee-making process and systematically remove all that is problematic in it. The result is something flawless, but that is a particular and limited form of excellence or perfection. Perhaps there are peaks above perfection that can be achieved only by accepting a certain amount of imperfection.", "sourceURL": "http://www.aeonmagazine.com/being-human/julian-baggini-coffee-artisans/", "sourceTitle": "Julian Baggini – The art of coffee", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "This uniqueness and singleness which distinguishes each individual and gives a meaning to his existence has a bearing on creative work as much as it does on human love. When the impossibility of replacing a person is realized, it allows the responsibility which a man has for his existence and its continuance to appear in all its magnitude. A man who becomes conscious of the responsibility he bears toward a human being who affectionately waits for him, or to an unfinished work, will never be able to throw away his life. He knows the \"why\" for his existence, and will be able to bear almost any \"how.\"", "sourceURL": "http://www.theatlantic.com/health/archive/2013/01/theres-more-to-life-than-being-happy/266805/", "sourceTitle": "There's More to Life Than Being Happy", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "What we found when we’d ask our testers about Snapchat is that they categorized it more as a game than as a utility,” he says. “When we asked one of our 19 year old testers about Snapchat, she responded ‘oh yeah I play that sometimes.’ For her, Snapchat exists somewhere between Angry Birds and Facebook.", "sourceURL": "http://www.buzzfeed.com/jwherrman/how-teens-are-taking-over-the-tech-world", "sourceTitle": "How Teens Are Taking Over The Tech World", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate(), "comment": "Adding to the pile for my “apps-as-entertainment” hypothesis."});
    	
    	var currentQuote = Quotes.insert({"text": "“The Primes of the Story,” which could be considered the certain hooks that you latch on to when rollicking about in someone else’s tale. What’s interesting is that you could interpret the primes of the story as the places where stories are unable to be forked. By saying so, you’d suggest that rather than keeping the formal structure of the story intact, you just keep the hooks in place.", "sourceURL": "http://www.themavenist.org/02-cartoons-forkedreality/index.html", "sourceTitle": "Cartoons & Forked Reality", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "You often never find out how good a product might have been. As I’ve gotten older and the world has gotten faster, the hardest thing to do has been to take the time to find that out, to create space for myself to screw around in speculative ways, to stay safe from criticism until I’ve hit upon something that really pleases me.", "sourceURL": "http://techcrunch.com/2012/12/31/the-maximum-beautiful-product/", "sourceTitle": "The Maximum, Beautiful Product | TechCrunch", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Maybe the reason we don’t have big ideas is because our entire approach to building them is sometimes so frugal with time, money, and belief. Lean startup techniques have revolutionized how we build software, but the lean startup has also turned the a startup’s only initial asset – the conviction that an idea will work — into a villain rather than the hero.", "sourceURL": "http://techcrunch.com/2012/12/31/the-maximum-beautiful-product/", "sourceTitle": "The Maximum, Beautiful Product | TechCrunch", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "He said that he liked to think Drop7 was not only addictive but also, on some level, about addiction. Games, he told me, are like “homebrew neuroscience” — “a little digital drug you can use to run experiments on your own brain.” Part of the point of letting them seduce you, as Lantz sees it, is to come out the other side a more interesting and self-aware person; more conscious of your habits, weaknesses, desires and strengths. “It’s like heroin that is abstracted or compressed or stylized,” he said. “It gives you a window into your brain that doesn’t crush your brain.”", "sourceURL": "http://www.nytimes.com/2012/04/08/magazine/angry-birds-farmville-and-other-hyperaddictive-stupid-games.html?pagewanted=all&_r=0", "sourceTitle": "Angry Birds, Farmville and Other Hyperaddictive ‘Stupid Games’ - NYTimes.com", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Sure, there’s mathematics to it, but it’s also a piece of culture. The type of game you play is also a part of how you think about yourself as a person. There’s no formula that’s going to solve that equation. It’s impossible, because it’s infinitely deep and wonderful.", "sourceURL": "http://www.nytimes.com/2012/04/08/magazine/angry-birds-farmville-and-other-hyperaddictive-stupid-games.html?pagewanted=all&_r=0", "sourceTitle": "Angry Birds, Farmville and Other Hyperaddictive ‘Stupid Games’ - NYTimes.com", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "At long last, I had found myself vulnerable to the worst of New York City, because at 44 my life was not so different from the way it was at 24. Stubbornly and proudly, emphatically and pathetically, I had refused to grow up, and so I was becoming one of those people who refuses to grow up—one of the city’s Lost Boys. I was still subletting in Greenwich Village, instead of owning in Brooklyn Heights. I had loved everything about Yale Law School—especially the part where I graduated at 40—but I spent my life savings on an abiding interest, which is a lot to invest in curiosity. By never marrying, I ended up never divorcing, but I also failed to accumulate that brocade of civility and padlock of security—kids you do or don’t want, Tiffany silver you never use—that makes life complete. Convention serves a purpose: It gives life meaning, and without it, one is in a constant existential crisis. If you don’t have the imposition of family to remind you of what is at stake, something else will. I was alone in a lonely apartment with only a stalker to show for my accomplishments and my years.", "sourceURL": "http://nymag.com/thecut/2013/01/elizabeth-wurtzel-on-self-help.html", "sourceTitle": "Elizabeth Wurtzel Confronts Her One-Night Stand of a Life", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Look at how we live: We communicate in text messages and e-mails; even those of us old enough to have lived in a world where landline was not a word because it’s all there was have fallen into this lazy substitute for human contact. I have. When I was young, when I was the age I should have been when all this happened, if I needed to tell a friend, an acquaintance, or the customer-service person from AT&T the smallest thing, I had to talk to him. Every day, many times a day, whether I felt like it or not, I spoke to people, lots of people. It is as obvious from a voice as it is not from print if all is well. Now, in a whole long day of croissants in the morning and multiple dog walks and stops at the bodega for yogurt and jam, I may speak with people I care about only in type. When you add the mistake of Facebook and Twitter into this equation, very bad things can happen: The illusion of friendship defeats the real thing.", "sourceURL": "http://nymag.com/thecut/2013/01/elizabeth-wurtzel-on-self-help.html", "sourceTitle": "Elizabeth Wurtzel Confronts Her One-Night Stand of a Life", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Design as a discipline is challenged by this notion of democracy, particularly in a viral age. We have become a culture mistrustful of expertise—in particular creative expertise. I share Correa's fear that this cultural position stifles design as designers increasingly lose ownership of the discourse. \"If deep knowledge in these fields is weighed against the \"likes\" and \"tastes\" of the populace at large,\" she warns, \"We will create a climate that does not encourage visual or aesthetic exploration, play or inventiveness, since the new is often soundly refused.\"", "sourceURL": "http://www.rockpaperink.com/content/column.php?id=468", "sourceTitle": "The UC Logo Controversy: How 54,000 people, the mainstream press, and virtually every designer got it wrong. - RockPaperInk", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Yes, once again, designers are the problem. I'm not talking about the designers who created this surprisingly controversial identity. I'm talking about everyone else. I'm talking about the haters. Designers who want the profession (and themselves) to be taken seriously need to be asking questions that get to the core of the motivations and goals that frame a project before passing judgment on the outcome. Otherwise our 'criticism' is also simply subjective. And if and when we do criticize the work of fellow professionals, we should strive to do so in an informed and civil manner. That sounds like advice your mother might give you, but it actually comes from AIGA's Guide to Professional Ethics: \"A professional designer shall be objective and balanced in criticizing another designer's work and shall not denigrate the work or reputation of a fellow designer.\" Writing \"the logo sucks\" many garner a bevy of Facebook 'likes' but it doesn't do any favors for our professional profile.", "sourceURL": "http://www.rockpaperink.com/content/column.php?id=468", "sourceTitle": "The UC Logo Controversy: How 54,000 people, the mainstream press, and virtually every designer got it wrong. - RockPaperInk", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Aha! That's it! It's never been easier to learn a new skill. Never been easier to find and follow someone else's 'best practices.' To mimic the well-worn path of someone who came before you. And that's the potential trap - breakthroughs come not just from following instructions to minimize the time spent learning, but sometimes from the struggle, from pushing not down the riverbed where water has already flowed, but carving into hard earth. Is it possible that it's never been easier to be, well, average? If everyone is learning the same information and studying the same approach, yes the floor rises - we're all more educated - but what about the ceiling? Who will push outside of the boundaries? Who will remember that in addition to acquiring a skill, education is about learning how to learn. Does expedient, always-available instruction make it too easy?", "sourceURL": "http://www.hunterwalk.com/2013/01/welcome-to-2013-where-its-never-been.html?m=1", "sourceTitle": "Elapsed Time: Welcome to 2013, Where It's Never Been Easier to be Average", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "Each issue is a feast, so well curated—around 100 excerpts and many small squibs in issues devoted to such relevant subjects as money, war, the family and the future—that reading it is like choosing among bonbons for the brain. It’s a kind of hip-hop mash-up of human wisdom. Half the fun is figuring out the rationale of the order the Laphamites have given to the excerpts, which jump back and forth between millennia and genres", "sourceURL": "http://www.smithsonianmag.com/arts-culture/Lewis-Laphams-Antidote-to-the-Age-of-Buzzfeed-174943751.html?device=ipad", "sourceTitle": "Lewis Lapham’s Antidote to the Age of BuzzFeed", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "In some ways the speed and ease and volume of texts have devalued the content, but in others texting and IMing and g-chatting are improvisational evolutions of letter-writing, making it automatic and collaborative, not single-handed and static. Making it, in one word, hotter.", "sourceURL": "http://thenewinquiry.com/essays/speaking-in-tongues/", "sourceTitle": "Speaking in Tongues – The New Inquiry", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "It’s easy to share, to broadcast, to put our selves and our tastes and our identity performances out into the world for others to consume; what feedback and friendship we get in return comes in response to comparatively little effort and investment from us. It takes a lot more work, however, to do the consumption, to sift through everything all (or even just some) of our friends produce, to do the work of connecting to our friends’ generalized broadcasts so that we can convert their depersonalized shares into meaningful friendship-labor.", "sourceURL": "http://thesocietypages.org/cyborgology/2012/12/18/the-devolution-of-friendship-full-essay-pts-i-ii/", "sourceTitle": "Social Media and the Devolution of Friendship: Full Essay (Pts I & II) » Cyborgology", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "devolved friendship’s attendant depersonalization deserves attention. When we consider the lopsided rationalization of ‘sharing’ and ‘shared with,’ as well as the depersonalization of frictionless sharing and generalized broadcasting, what becomes clear is this: the social media deck is stacked in such a way as to make being ‘a self’ easier and more rewarding than being ‘a friend.’", "sourceURL": "http://thesocietypages.org/cyborgology/2012/12/18/the-devolution-of-friendship-full-essay-pts-i-ii/", "sourceTitle": "Social Media and the Devolution of Friendship: Full Essay (Pts I & II) » Cyborgology", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    	var currentQuote = Quotes.insert({"text": "If you want to build a ship, don't drum up people together to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.", "sourceURL": "http://imprint.printmag.com/daily-heller/surgical-design-for-surgical-equipment/", "sourceTitle": "Designing a Better Medical Device: A Q&A with Intuitive Surgical", "date": moment().toDate(), "user": "ninakix"});
    	QuoteUsers.insert({"user": "ninakix", "quote": currentQuote, "date": moment().toDate()});
    	
    }
    

});

